apiVersion: v1
kind: Service
metadata:
  name: cloud-model-svc
  namespace: production
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: grpc
      port: 9500
      protocol: TCP
      targetPort: 9500
  selector:
    seldon-app-svc: cloud-model-default-cloud-model
  sessionAffinity: None
  type: LoadBalancer
status:
