apiVersion: v1
kind: Pod
metadata:
  name: hello-example
spec:
  containers:
    - name: hello-example
      image: seldonio/mock_classifier:1.5.0
  initContainers:
    - name: hello-example-init
      image: busybox:1.28
      command: ["sh", "-c", "echo The app is running! && sleep 30"]
  nodeName: edge-compute
