name: classifier
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pip:
      - git+https://github.com/SachinVarghese/tempo.git@daab2241ba9cecaee69481e3f06acea9005e0f2f
      - mlserver==0.3.2
